### ISSUE TITLE
About Amanda's specifications

### ISSUE THREAD

**Issue by rika1110** [zmanda/amanda#238]
Hello everyone. Please tell me about Amanda.
Is it possible to take a system image backup of a Windows Server using Amanda Community?
Which backup method does Amanda Community use, file-based or image-based?

**Comment by rishabh-trivedi98** [comment]
Hi @rika1110,

Amanda Community Edition is a version of Amanda that is freely available and designed for small to medium-sized environments.

Amanda primarily uses a file-based backup approach. It focuses on backing up files, directories, and data from systems rather than creating complete system image backups. While it can capture snapshots of your data and perform backups that encompass your entire system, it's not primarily designed as an "image-based" backup solution like some other tools.

For Windows servers, Amanda Community Edition can help you back up your data and directories effectively. You can get more information on https://wiki.zmanda.com/index.php/Main_Page. The Windows client is available with amanda version 3.3.6 which can be helpful in taking system state backup for windows server. However, for later versions, the Windows client is now offered as part of Zmanda.

Thanks you.
